### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by lrferreiro** [13302296C/flutter_rte#3]
Hello, first of all thanks for this plugin, it is excellent. But I think it should have some way to at least validate if it's empty or not, or a validator like TextFormField does. Thanks greetings.

**Comment by pavel604** [comment]
HI, @lrferreiro, and thanks for the feedback.

you could use `controller.contentIsEmpty` or `controller.content.isEmpty` etc. Just keep in mind that an empty paragraph HTML (i.e. `<p><br></p>`) is not an empty string.

Validator is a great idea to add.

Thanks.
