### ISSUE TITLE
wrap up toolBar at custom position

### ISSUE THREAD

**Issue by dangmt-se** [13302296C/flutter_rte#4]
Hi, thank you so much for such a state of the art plug-in.
I'm trying to make the toolbar adjustable to the size of the page/ container I plugged it in but still failed to do so.
Would you please let me know where and how I can customize the width of the toolbar? or have a dropdown menu if the width is minimized?
Thank you.

**Comment by pavel604** [comment]
Hi @dangmt-se . Please check the code [example](https://github.com/13302296C/flutter_rte/tree/master/example) that comes with the package - that should help with what you are trying to do.

**Comment by dangmt-se** [comment]
Thank you for getting back to me!

**Comment by dangmt-se** [comment]
> Hi @dangmt-se . Please check the code [example](https://github.com/13302296C/flutter_rte/tree/master/example) that comes with the package - that should help with what you are trying to do.

Sorry for disturbing you again. I inserted more table onto the toolbar and activate any relevant code that I can found but still failed to execute the table on the editor. Is there any specific place I have to look?

**Comment by pavel604** [comment]
Hey @dangmt-se. The options you are talking about are `HtmlEditorController > ToolbarOptions > toolbarType`. There you have `nativeGrid`, `nativeScrollable` or `nativeExpandable` I'm not quite sure what exactly you are trying to do, but if you think this is a bug - please provide a minimal reproducible example with a description of expected and observed behaviors.
